services:

  postgres:
    restart: always
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=realworld
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
