services:

  postgres:
    restart: always
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=realworld
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres-rel:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  realworld:
    image: ghcr.io/miueon/realworld-smithy4s:0.1.0-SNAPSHOT
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DEBUG=false
      - SC_APP_ENV=Prod
      - SC_ACCESS_TOKEN_KEY=5h0pp1ng_k4rt
      - SC_PASSWORD_SALT=06!grsnxXG0d*Pj496p6fuA*o
      - SC_POSTGRES_PASSWORD=123456
      - _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true"
volumes:
  postgres-rel:
    external: true