@port = 8080
@baseURL = http://127.0.0.1:{{port}}
###

PUT {{baseURL}}/api/users

{
  "user": {
  "username": "test",
  "email": "test@123.com",
  "password": "12345678"
  }
}
###
# @name login
POST {{baseURL}}/api/users/login

{
  "user": {
    "email": "test@123.com",
    "password": "12345678"
  }
}

@token = {{login.response.body.user.token}}
@auth = Token {{token}}
@username = {{login.response.body.user.username}}

###
# GET PROFILE
GET {{baseURL}}/api/profiles/{{username}}

###

GET {{baseURL}}/api/user
Authorization: {{auth}}
### Article
### Create
POST {{baseURL}}/api/articles
Authorization: {{auth}}

{
  "article": {
    "title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": ["reactjs", "angularjs", "dragons"]
  }
}

@slug = did-you-train-your-dragon-fuckjiajiaaaaacccc-8ab9900e-9fc5-41a2-953d-99ca782b7071-1708532529077

### Update
PUT {{baseURL}}/api/articles/{{slug}}
Authorization: {{auth}}

{
  "article": {
    "title": "Did you train your dragon?"
  }
}

### Get
GET {{baseURL}}/api/article/{{slug}}