@port = 8080
@baseURL = http://127.0.0.1:{{port}}
GET {{baseURL}}/api/user
###

PUT {{baseURL}}/api/users

{
  "user": {
  "username": "test",
  "email": "test@123.com",
  "password": "12345678"
  }
}

###
POST {{baseURL}}/api/users/login

{
  "user": {
    "email": "test@123.com",
    "password": "12345678"
  }
}