@port = 8080
@baseURL = http://127.0.0.1:{{port}}

@failedU = {"user": { "username": "test2" ,  "email": "com", "password": "12345678"}}
###
# REGISTER  
PUT {{baseURL}}/api/users

{{failedU}}
@u1 = {"user": {    "email": "test@123.com","password": "12345678"}}
@u2 = {"user": {    "email": "test2@123.com", "password": "12345678"}}
###
# @name login
POST {{baseURL}}/api/users/login

{{u2}}

@token = {{login.response.body.user.token}}
@auth = Token {{token}}
@username = {{login.response.body.user.username}}
@u1name = test

###
# GET PROFILE
GET {{baseURL}}/api/profiles/{{u1name}}
Authorization: {{auth}}


### Follow
POST {{baseURL}}/api/profiles/{{u1name}}/follow
Authorization: {{auth}}
###

### Unfollow
DELETE {{baseURL}}/api/profiles/{{u1name}}/follow
Authorization: {{auth}}

GET {{baseURL}}/api/user
Authorization: {{auth}}
### Article
### Create
POST {{baseURL}}/api/articles
Authorization: {{auth}}

{
  "article": {
    "title": "How to train your dragon 176",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": ["reactjs", "angularjs", "dragons"]
  }
}

@slug = how-to-train-your-dragon-8ab9900e-9fc5-41a2-953d-99ca782b7071-1708579842391

### Update
PUT {{baseURL}}/api/articles/{{slug}}
Authorization: {{auth}}

{
  "article": {
    "title": "Did you train your dragon?"
  }
}

### Get
GET {{baseURL}}/api/article/{{slug}}

### List Feed
GET {{baseURL}}/api/articles/feed
Authorization: {{auth}}

### Fav
POST  {{baseURL}}/api/articles/{{slug}}/favorite
Authorization: {{auth}}

### Unfav
DELETE {{baseURL}}/api/articles/{{slug}}/favorite
Authorization: {{auth}}

### Delete
DELETE {{baseURL}}/api/articles/{{slug}}
Authorization: {{auth}}

### Tag
### Get
GET {{baseURL}}/api/tags


### Comment
### Create 
POST {{baseURL}}/api/articles/{{slug}}/comments
Authorization: {{auth}}

{
  "comment": {
    "body": "His name was my name too."
  }
}

### Get All
GET {{baseURL}}/api/articles/{{slug}}/comments
Authorization: {{auth}}

### Delete
DELETE  {{baseURL}}/api/articles/{{slug}}/comments/1
Authorization: {{auth}}

