apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  postgres-password: "123456"
  SC_ACCESS_TOKEN_KEY: "5h0pp1ng_k4rt"
  SC_PASSWORD_SALT: "06!grsnxXG0d*Pj496p6fuA*o"
  SC_POSTGRES_PASSWORD: "123456"