apiVersion: v1
kind: Service
metadata:
  name: realworld-app # Updated to match ingress backend
  labels:
    app: realworld
spec:
  selector:
    app: realworld
  ports:
    - protocol: TCP
      port: 80 # Ingress expects port 80
      targetPort: 8080 # Container port
  type: ClusterIP # Changed to ClusterIP since we're using ingress
